# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rs_riggingtool_ui.ui'
#
# Created: Fri Sep 22 15:56:00 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class rs_riggingtool_ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 889)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(0, 25, 361, 681))
        self.toolBox.setMinimumSize(QtCore.QSize(231, 0))
        self.toolBox.setCursor(QtCore.Qt.ArrowCursor)
        self.toolBox.setMouseTracking(False)
        self.toolBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBox.setAcceptDrops(False)
        self.toolBox.setToolTip("")
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.toolBox.setObjectName("toolBox")
        self.CreateUpperGroup_3 = QtGui.QWidget()
        self.CreateUpperGroup_3.setGeometry(QtCore.QRect(0, 0, 361, 492))
        self.CreateUpperGroup_3.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.CreateUpperGroup_3.setObjectName("CreateUpperGroup_3")
        self.layoutWidget_19 = QtGui.QWidget(self.CreateUpperGroup_3)
        self.layoutWidget_19.setGeometry(QtCore.QRect(0, 0, 135, 70))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_19)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupname_le = QtGui.QLineEdit(self.layoutWidget_19)
        self.groupname_le.setObjectName("groupname_le")
        self.verticalLayout_5.addWidget(self.groupname_le)
        self.creategroupname_pb = QtGui.QPushButton(self.layoutWidget_19)
        self.creategroupname_pb.setObjectName("creategroupname_pb")
        self.verticalLayout_5.addWidget(self.creategroupname_pb)
        self.toolBox.addItem(self.CreateUpperGroup_3, "")
        self.JointOnSelection_3 = QtGui.QWidget()
        self.JointOnSelection_3.setGeometry(QtCore.QRect(0, 0, 361, 492))
        self.JointOnSelection_3.setObjectName("JointOnSelection_3")
        self.layoutWidget_20 = QtGui.QWidget(self.JointOnSelection_3)
        self.layoutWidget_20.setGeometry(QtCore.QRect(0, 0, 231, 110))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.gridLayout_25 = QtGui.QGridLayout(self.layoutWidget_20)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_26 = QtGui.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.childobj_le = QtGui.QLineEdit(self.layoutWidget_20)
        self.childobj_le.setObjectName("childobj_le")
        self.gridLayout_26.addWidget(self.childobj_le, 0, 0, 1, 1)
        self.parentobj_le = QtGui.QLineEdit(self.layoutWidget_20)
        self.parentobj_le.setObjectName("parentobj_le")
        self.gridLayout_26.addWidget(self.parentobj_le, 1, 0, 1, 1)
        self.gridLayout_27 = QtGui.QGridLayout()
        self.gridLayout_27.setSpacing(6)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_30 = QtGui.QLabel(self.layoutWidget_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_27.addWidget(self.label_30, 0, 0, 1, 1)
        self.centerofobj_cb = QtGui.QCheckBox(self.layoutWidget_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.centerofobj_cb.setFont(font)
        self.centerofobj_cb.setObjectName("centerofobj_cb")
        self.gridLayout_27.addWidget(self.centerofobj_cb, 0, 1, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_27, 2, 0, 1, 1)
        self.getparent_pb = QtGui.QPushButton(self.layoutWidget_20)
        self.getparent_pb.setObjectName("getparent_pb")
        self.gridLayout_26.addWidget(self.getparent_pb, 1, 1, 1, 1)
        self.getchild_pb = QtGui.QPushButton(self.layoutWidget_20)
        self.getchild_pb.setObjectName("getchild_pb")
        self.gridLayout_26.addWidget(self.getchild_pb, 0, 1, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_26, 0, 0, 1, 1)
        self.createjoinandskin_pb = QtGui.QPushButton(self.layoutWidget_20)
        self.createjoinandskin_pb.setObjectName("createjoinandskin_pb")
        self.gridLayout_25.addWidget(self.createjoinandskin_pb, 1, 0, 1, 1)
        self.toolBox.addItem(self.JointOnSelection_3, "")
        self.toolBoxPage3_3 = QtGui.QWidget()
        self.toolBoxPage3_3.setGeometry(QtCore.QRect(0, 0, 361, 492))
        self.toolBoxPage3_3.setObjectName("toolBoxPage3_3")
        self.layoutWidget_21 = QtGui.QWidget(self.toolBoxPage3_3)
        self.layoutWidget_21.setGeometry(QtCore.QRect(0, 0, 218, 87))
        self.layoutWidget_21.setObjectName("layoutWidget_21")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_21)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.animateobj_le = QtGui.QLineEdit(self.layoutWidget_21)
        self.animateobj_le.setObjectName("animateobj_le")
        self.horizontalLayout_6.addWidget(self.animateobj_le)
        self.getinput_pb = QtGui.QPushButton(self.layoutWidget_21)
        self.getinput_pb.setObjectName("getinput_pb")
        self.horizontalLayout_6.addWidget(self.getinput_pb)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ctrl_le = QtGui.QLineEdit(self.layoutWidget_21)
        self.ctrl_le.setObjectName("ctrl_le")
        self.horizontalLayout_7.addWidget(self.ctrl_le)
        self.setctrl_pb = QtGui.QPushButton(self.layoutWidget_21)
        self.setctrl_pb.setObjectName("setctrl_pb")
        self.horizontalLayout_7.addWidget(self.setctrl_pb)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.connect_pb = QtGui.QPushButton(self.layoutWidget_21)
        self.connect_pb.setObjectName("connect_pb")
        self.verticalLayout_6.addWidget(self.connect_pb)
        self.toolBox.addItem(self.toolBoxPage3_3, "")
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 361, 492))
        self.page_9.setObjectName("page_9")
        self.layoutWidget_22 = QtGui.QWidget(self.page_9)
        self.layoutWidget_22.setGeometry(QtCore.QRect(0, 0, 191, 94))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self.gridLayout_28 = QtGui.QGridLayout(self.layoutWidget_22)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.sneer_cb = QtGui.QCheckBox(self.layoutWidget_22)
        self.sneer_cb.setObjectName("sneer_cb")
        self.gridLayout_28.addWidget(self.sneer_cb, 1, 1, 1, 1)
        self.toonyjaw_cb = QtGui.QCheckBox(self.layoutWidget_22)
        self.toonyjaw_cb.setObjectName("toonyjaw_cb")
        self.gridLayout_28.addWidget(self.toonyjaw_cb, 1, 0, 1, 1)
        self.lip_cb = QtGui.QCheckBox(self.layoutWidget_22)
        self.lip_cb.setObjectName("lip_cb")
        self.gridLayout_28.addWidget(self.lip_cb, 0, 0, 1, 1)
        self.setup_pb = QtGui.QPushButton(self.layoutWidget_22)
        self.setup_pb.setObjectName("setup_pb")
        self.gridLayout_28.addWidget(self.setup_pb, 2, 0, 1, 1)
        self.build_pb = QtGui.QPushButton(self.layoutWidget_22)
        self.build_pb.setObjectName("build_pb")
        self.gridLayout_28.addWidget(self.build_pb, 2, 1, 1, 1)
        self.brow_cb = QtGui.QCheckBox(self.layoutWidget_22)
        self.brow_cb.setObjectName("brow_cb")
        self.gridLayout_28.addWidget(self.brow_cb, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_9, "")
        self.page_10 = QtGui.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 361, 492))
        self.page_10.setObjectName("page_10")
        self.layoutWidget_23 = QtGui.QWidget(self.page_10)
        self.layoutWidget_23.setGeometry(QtCore.QRect(0, 0, 241, 25))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.gridLayout_29 = QtGui.QGridLayout(self.layoutWidget_23)
        self.gridLayout_29.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.proxy_le = QtGui.QLineEdit(self.layoutWidget_23)
        self.proxy_le.setObjectName("proxy_le")
        self.gridLayout_29.addWidget(self.proxy_le, 0, 0, 1, 1)
        self.selectproxygrp_pb = QtGui.QPushButton(self.layoutWidget_23)
        self.selectproxygrp_pb.setObjectName("selectproxygrp_pb")
        self.gridLayout_29.addWidget(self.selectproxygrp_pb, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_10, "")
        self.page_11 = QtGui.QWidget()
        self.page_11.setGeometry(QtCore.QRect(0, 0, 361, 492))
        self.page_11.setObjectName("page_11")
        self.line_11 = QtGui.QFrame(self.page_11)
        self.line_11.setGeometry(QtCore.QRect(-10, 110, 321, 16))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtGui.QFrame(self.page_11)
        self.line_12.setGeometry(QtCore.QRect(0, 232, 321, 18))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtGui.QFrame(self.page_11)
        self.line_13.setGeometry(QtCore.QRect(0, 234, 321, 18))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.layoutWidget_24 = QtGui.QWidget(self.page_11)
        self.layoutWidget_24.setGeometry(QtCore.QRect(0, 1, 293, 112))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.gridLayout_30 = QtGui.QGridLayout(self.layoutWidget_24)
        self.gridLayout_30.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_31 = QtGui.QLabel(self.layoutWidget_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_30.addWidget(self.label_31, 0, 0, 1, 1)
        self.sourcetranslate_le = QtGui.QLineEdit(self.layoutWidget_24)
        self.sourcetranslate_le.setInputMask("")
        self.sourcetranslate_le.setText("")
        self.sourcetranslate_le.setObjectName("sourcetranslate_le")
        self.gridLayout_30.addWidget(self.sourcetranslate_le, 0, 1, 1, 1)
        self.pushButton_61 = QtGui.QPushButton(self.layoutWidget_24)
        self.pushButton_61.setObjectName("pushButton_61")
        self.gridLayout_30.addWidget(self.pushButton_61, 0, 2, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_30.addWidget(self.label_32, 1, 0, 1, 1)
        self.sourcerotate_le = QtGui.QLineEdit(self.layoutWidget_24)
        self.sourcerotate_le.setInputMask("")
        self.sourcerotate_le.setText("")
        self.sourcerotate_le.setObjectName("sourcerotate_le")
        self.gridLayout_30.addWidget(self.sourcerotate_le, 1, 1, 1, 1)
        self.pushButton_62 = QtGui.QPushButton(self.layoutWidget_24)
        self.pushButton_62.setObjectName("pushButton_62")
        self.gridLayout_30.addWidget(self.pushButton_62, 1, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_30.addWidget(self.label_33, 2, 0, 1, 1)
        self.sourcescale_le = QtGui.QLineEdit(self.layoutWidget_24)
        self.sourcescale_le.setInputMask("")
        self.sourcescale_le.setText("")
        self.sourcescale_le.setObjectName("sourcescale_le")
        self.gridLayout_30.addWidget(self.sourcescale_le, 2, 1, 1, 1)
        self.pushButton_63 = QtGui.QPushButton(self.layoutWidget_24)
        self.pushButton_63.setObjectName("pushButton_63")
        self.gridLayout_30.addWidget(self.pushButton_63, 2, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_30.addWidget(self.label_34, 3, 0, 1, 1)
        self.sourcevis_le = QtGui.QLineEdit(self.layoutWidget_24)
        self.sourcevis_le.setInputMask("")
        self.sourcevis_le.setText("")
        self.sourcevis_le.setObjectName("sourcevis_le")
        self.gridLayout_30.addWidget(self.sourcevis_le, 3, 1, 1, 1)
        self.pushButton_64 = QtGui.QPushButton(self.layoutWidget_24)
        self.pushButton_64.setObjectName("pushButton_64")
        self.gridLayout_30.addWidget(self.pushButton_64, 3, 2, 1, 1)
        self.layoutWidget_25 = QtGui.QWidget(self.page_11)
        self.layoutWidget_25.setGeometry(QtCore.QRect(0, 122, 292, 112))
        self.layoutWidget_25.setObjectName("layoutWidget_25")
        self.gridLayout_31 = QtGui.QGridLayout(self.layoutWidget_25)
        self.gridLayout_31.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_35 = QtGui.QLabel(self.layoutWidget_25)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_31.addWidget(self.label_35, 0, 0, 1, 1)
        self.destinationtranslate_le = QtGui.QLineEdit(self.layoutWidget_25)
        self.destinationtranslate_le.setInputMask("")
        self.destinationtranslate_le.setText("")
        self.destinationtranslate_le.setObjectName("destinationtranslate_le")
        self.gridLayout_31.addWidget(self.destinationtranslate_le, 0, 1, 1, 1)
        self.pushButton_65 = QtGui.QPushButton(self.layoutWidget_25)
        self.pushButton_65.setObjectName("pushButton_65")
        self.gridLayout_31.addWidget(self.pushButton_65, 0, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget_25)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_31.addWidget(self.label_36, 1, 0, 1, 1)
        self.destinationrotate_le = QtGui.QLineEdit(self.layoutWidget_25)
        self.destinationrotate_le.setInputMask("")
        self.destinationrotate_le.setText("")
        self.destinationrotate_le.setObjectName("destinationrotate_le")
        self.gridLayout_31.addWidget(self.destinationrotate_le, 1, 1, 1, 1)
        self.pushButton_66 = QtGui.QPushButton(self.layoutWidget_25)
        self.pushButton_66.setObjectName("pushButton_66")
        self.gridLayout_31.addWidget(self.pushButton_66, 1, 2, 1, 1)
        self.label_37 = QtGui.QLabel(self.layoutWidget_25)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_31.addWidget(self.label_37, 2, 0, 1, 1)
        self.destinationscale_le = QtGui.QLineEdit(self.layoutWidget_25)
        self.destinationscale_le.setInputMask("")
        self.destinationscale_le.setText("")
        self.destinationscale_le.setObjectName("destinationscale_le")
        self.gridLayout_31.addWidget(self.destinationscale_le, 2, 1, 1, 1)
        self.pushButton_67 = QtGui.QPushButton(self.layoutWidget_25)
        self.pushButton_67.setObjectName("pushButton_67")
        self.gridLayout_31.addWidget(self.pushButton_67, 2, 2, 1, 1)
        self.label_38 = QtGui.QLabel(self.layoutWidget_25)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_31.addWidget(self.label_38, 3, 0, 1, 1)
        self.destinationvisibility_le = QtGui.QLineEdit(self.layoutWidget_25)
        self.destinationvisibility_le.setInputMask("")
        self.destinationvisibility_le.setText("")
        self.destinationvisibility_le.setObjectName("destinationvisibility_le")
        self.gridLayout_31.addWidget(self.destinationvisibility_le, 3, 1, 1, 1)
        self.pushButton_68 = QtGui.QPushButton(self.layoutWidget_25)
        self.pushButton_68.setObjectName("pushButton_68")
        self.gridLayout_31.addWidget(self.pushButton_68, 3, 2, 1, 1)
        self.layoutWidget_26 = QtGui.QWidget(self.page_11)
        self.layoutWidget_26.setGeometry(QtCore.QRect(0, 247, 353, 83))
        self.layoutWidget_26.setObjectName("layoutWidget_26")
        self.gridLayout_32 = QtGui.QGridLayout(self.layoutWidget_26)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.label_39 = QtGui.QLabel(self.layoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_32.addWidget(self.label_39, 0, 0, 1, 1)
        self.sourceattribute_le = QtGui.QLineEdit(self.layoutWidget_26)
        self.sourceattribute_le.setText("")
        self.sourceattribute_le.setObjectName("sourceattribute_le")
        self.gridLayout_32.addWidget(self.sourceattribute_le, 0, 1, 1, 1)
        self.setsource_pb = QtGui.QPushButton(self.layoutWidget_26)
        self.setsource_pb.setObjectName("setsource_pb")
        self.gridLayout_32.addWidget(self.setsource_pb, 0, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.layoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_32.addWidget(self.label_40, 1, 0, 1, 1)
        self.destinationattribute_le = QtGui.QLineEdit(self.layoutWidget_26)
        self.destinationattribute_le.setText("")
        self.destinationattribute_le.setObjectName("destinationattribute_le")
        self.gridLayout_32.addWidget(self.destinationattribute_le, 1, 1, 1, 1)
        self.setdestination_pb = QtGui.QPushButton(self.layoutWidget_26)
        self.setdestination_pb.setObjectName("setdestination_pb")
        self.gridLayout_32.addWidget(self.setdestination_pb, 1, 2, 1, 1)
        self.transferattribute_pb = QtGui.QPushButton(self.layoutWidget_26)
        self.transferattribute_pb.setObjectName("transferattribute_pb")
        self.gridLayout_32.addWidget(self.transferattribute_pb, 2, 1, 1, 1)
        self.toolBox.addItem(self.page_11, "")
        self.page_12 = QtGui.QWidget()
        self.page_12.setGeometry(QtCore.QRect(0, 0, 361, 492))
        self.page_12.setObjectName("page_12")
        self.layoutWidget_27 = QtGui.QWidget(self.page_12)
        self.layoutWidget_27.setGeometry(QtCore.QRect(0, 1, 224, 263))
        self.layoutWidget_27.setObjectName("layoutWidget_27")
        self.gridLayout_33 = QtGui.QGridLayout(self.layoutWidget_27)
        self.gridLayout_33.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.gridLayout_34 = QtGui.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.label_41 = QtGui.QLabel(self.layoutWidget_27)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_34.addWidget(self.label_41, 0, 0, 1, 1)
        self.rename_le = QtGui.QLineEdit(self.layoutWidget_27)
        self.rename_le.setObjectName("rename_le")
        self.gridLayout_34.addWidget(self.rename_le, 0, 1, 1, 1)
        self.rename_pb = QtGui.QPushButton(self.layoutWidget_27)
        self.rename_pb.setObjectName("rename_pb")
        self.gridLayout_34.addWidget(self.rename_pb, 1, 0, 1, 2)
        self.gridLayout_33.addLayout(self.gridLayout_34, 0, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.layoutWidget_27)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_33.addWidget(self.line_14, 1, 0, 1, 1)
        self.gridLayout_35 = QtGui.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.name_le = QtGui.QLineEdit(self.layoutWidget_27)
        self.name_le.setObjectName("name_le")
        self.gridLayout_35.addWidget(self.name_le, 0, 0, 1, 3)
        self.ctrlname_le = QtGui.QLineEdit(self.layoutWidget_27)
        self.ctrlname_le.setObjectName("ctrlname_le")
        self.gridLayout_35.addWidget(self.ctrlname_le, 1, 0, 1, 2)
        self.destination_pb = QtGui.QPushButton(self.layoutWidget_27)
        self.destination_pb.setObjectName("destination_pb")
        self.gridLayout_35.addWidget(self.destination_pb, 1, 2, 1, 1)
        self.suffix_cb = QtGui.QRadioButton(self.layoutWidget_27)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.suffix_cb.setFont(font)
        self.suffix_cb.setObjectName("suffix_cb")
        self.gridLayout_35.addWidget(self.suffix_cb, 2, 0, 1, 1)
        self.prefix_cb = QtGui.QRadioButton(self.layoutWidget_27)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.prefix_cb.setFont(font)
        self.prefix_cb.setObjectName("prefix_cb")
        self.gridLayout_35.addWidget(self.prefix_cb, 2, 1, 1, 2)
        self.add_pb = QtGui.QPushButton(self.layoutWidget_27)
        self.add_pb.setObjectName("add_pb")
        self.gridLayout_35.addWidget(self.add_pb, 3, 0, 1, 3)
        self.gridLayout_33.addLayout(self.gridLayout_35, 2, 0, 1, 1)
        self.line_15 = QtGui.QFrame(self.layoutWidget_27)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_33.addWidget(self.line_15, 3, 0, 1, 1)
        self.gridLayout_36 = QtGui.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.label_42 = QtGui.QLabel(self.layoutWidget_27)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_36.addWidget(self.label_42, 0, 0, 1, 1)
        self.searchname_le = QtGui.QLineEdit(self.layoutWidget_27)
        self.searchname_le.setObjectName("searchname_le")
        self.gridLayout_36.addWidget(self.searchname_le, 0, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.layoutWidget_27)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_36.addWidget(self.label_43, 1, 0, 1, 1)
        self.replacename_le = QtGui.QLineEdit(self.layoutWidget_27)
        self.replacename_le.setObjectName("replacename_le")
        self.gridLayout_36.addWidget(self.replacename_le, 1, 1, 1, 1)
        self.searchreplace_pb = QtGui.QPushButton(self.layoutWidget_27)
        self.searchreplace_pb.setObjectName("searchreplace_pb")
        self.gridLayout_36.addWidget(self.searchreplace_pb, 2, 0, 1, 2)
        self.gridLayout_33.addLayout(self.gridLayout_36, 4, 0, 1, 1)
        self.toolBox.addItem(self.page_12, "")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 114, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupname_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Enter Group Name", None, QtGui.QApplication.UnicodeUTF8))
        self.creategroupname_pb.setText(QtGui.QApplication.translate("MainWindow", "Create UpperGroup", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.CreateUpperGroup_3), QtGui.QApplication.translate("MainWindow", "Create Upper Group", None, QtGui.QApplication.UnicodeUTF8))
        self.childobj_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Child Object", None, QtGui.QApplication.UnicodeUTF8))
        self.parentobj_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Parent Object", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Pivot - ", None, QtGui.QApplication.UnicodeUTF8))
        self.centerofobj_cb.setText(QtGui.QApplication.translate("MainWindow", "Center of Object", None, QtGui.QApplication.UnicodeUTF8))
        self.getparent_pb.setText(QtGui.QApplication.translate("MainWindow", "Get Parent", None, QtGui.QApplication.UnicodeUTF8))
        self.getchild_pb.setText(QtGui.QApplication.translate("MainWindow", "Get Child", None, QtGui.QApplication.UnicodeUTF8))
        self.createjoinandskin_pb.setText(QtGui.QApplication.translate("MainWindow", "Create Joint and Skin", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.JointOnSelection_3), QtGui.QApplication.translate("MainWindow", "Joint On Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.animateobj_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Animate Object", None, QtGui.QApplication.UnicodeUTF8))
        self.getinput_pb.setText(QtGui.QApplication.translate("MainWindow", "Get Input", None, QtGui.QApplication.UnicodeUTF8))
        self.ctrl_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.setctrl_pb.setText(QtGui.QApplication.translate("MainWindow", "Set CTRL", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_pb.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage3_3), QtGui.QApplication.translate("MainWindow", "Connect Attr", None, QtGui.QApplication.UnicodeUTF8))
        self.sneer_cb.setText(QtGui.QApplication.translate("MainWindow", "Sneer/Muzzle", None, QtGui.QApplication.UnicodeUTF8))
        self.toonyjaw_cb.setText(QtGui.QApplication.translate("MainWindow", "Toony Jaw", None, QtGui.QApplication.UnicodeUTF8))
        self.lip_cb.setText(QtGui.QApplication.translate("MainWindow", "Lips/Lips Mover", None, QtGui.QApplication.UnicodeUTF8))
        self.setup_pb.setText(QtGui.QApplication.translate("MainWindow", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.build_pb.setText(QtGui.QApplication.translate("MainWindow", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.brow_cb.setText(QtGui.QApplication.translate("MainWindow", "EyeBrows", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), QtGui.QApplication.translate("MainWindow", "Facial Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Proxy Group", None, QtGui.QApplication.UnicodeUTF8))
        self.selectproxygrp_pb.setText(QtGui.QApplication.translate("MainWindow", "Select Proxy Group", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_10), QtGui.QApplication.translate("MainWindow", "Create Proxy Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Translate:", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcetranslate_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "       0,      0,      0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_61.setText(QtGui.QApplication.translate("MainWindow", "Get Trans Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Rotate:", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcerotate_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "       0,      0,      0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_62.setText(QtGui.QApplication.translate("MainWindow", "Get Rotate Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcescale_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "       0,      0,      0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_63.setText(QtGui.QApplication.translate("MainWindow", "Get Scale Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Visibility:", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcevis_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "             On,Off", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_64.setText(QtGui.QApplication.translate("MainWindow", "Get Visibility Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Translate:", None, QtGui.QApplication.UnicodeUTF8))
        self.destinationtranslate_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "       0,      0,      0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_65.setText(QtGui.QApplication.translate("MainWindow", "Set Trans Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Rotate:", None, QtGui.QApplication.UnicodeUTF8))
        self.destinationrotate_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "       0,      0,      0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_66.setText(QtGui.QApplication.translate("MainWindow", "Set Rotate Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.destinationscale_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "       0,      0,      0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_67.setText(QtGui.QApplication.translate("MainWindow", "Set Scale Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Visibility:", None, QtGui.QApplication.UnicodeUTF8))
        self.destinationvisibility_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "             On,Off", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_68.setText(QtGui.QApplication.translate("MainWindow", "Set Visibility Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Source CTRL:", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceattribute_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Set Source Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.setsource_pb.setText(QtGui.QApplication.translate("MainWindow", "Set Source CTRL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Destination CTRL:", None, QtGui.QApplication.UnicodeUTF8))
        self.destinationattribute_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Set Destination CTRL", None, QtGui.QApplication.UnicodeUTF8))
        self.setdestination_pb.setText(QtGui.QApplication.translate("MainWindow", "Set Destination CTRL", None, QtGui.QApplication.UnicodeUTF8))
        self.transferattribute_pb.setText(QtGui.QApplication.translate("MainWindow", "Transfer Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_11), QtGui.QApplication.translate("MainWindow", "Transfer Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Rename:", None, QtGui.QApplication.UnicodeUTF8))
        self.rename_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Rename Object/CTRL", None, QtGui.QApplication.UnicodeUTF8))
        self.rename_pb.setText(QtGui.QApplication.translate("MainWindow", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.name_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.ctrlname_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "CTRL/Object", None, QtGui.QApplication.UnicodeUTF8))
        self.destination_pb.setText(QtGui.QApplication.translate("MainWindow", "Set Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.suffix_cb.setText(QtGui.QApplication.translate("MainWindow", "Suffix", None, QtGui.QApplication.UnicodeUTF8))
        self.prefix_cb.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.add_pb.setText(QtGui.QApplication.translate("MainWindow", "ADD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Search:", None, QtGui.QApplication.UnicodeUTF8))
        self.searchname_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Search Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Replace:", None, QtGui.QApplication.UnicodeUTF8))
        self.replacename_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Replace Name", None, QtGui.QApplication.UnicodeUTF8))
        self.searchreplace_pb.setText(QtGui.QApplication.translate("MainWindow", "Search and Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_12), QtGui.QApplication.translate("MainWindow", "Rename / Suffix / Prefix / Search / Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "rs_riggingtool", None, QtGui.QApplication.UnicodeUTF8))

